#!/usr/bin/env python3
"""Inspect the v5.0 governance decision log and emit JSON / Markdown / HTML reports.

The default mode prints a JSON summary to stdout. Use `--markdown-output <path>`
to write a Markdown report and `--html-output <path>` to write a self-contained
HTML dashboard. The HTML is rendered with a pure f-string template (no
external dependencies), so it can be opened in any browser without a server.

Usage:
    python scripts/inspect_decision_log.py [--repo <path>] [--pretty]
    python scripts/inspect_decision_log.py --markdown-output /tmp/report.md
    python scripts/inspect_decision_log.py --html-output /tmp/report.html
    python scripts/inspect_decision_log.py --markdown-output report.md \
                                           --html-output report.html --pretty

Exit codes:
    0 — success (the log was readable; counts may be zero)
    2 — fatal error (log path unwritable, config missing, etc.)
"""

from __future__ import annotations

import argparse
import json
import locale
import sys
from collections import Counter
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

SKILL_DIR = Path(__file__).resolve().parents[1]
DEFAULT_LOG_PATH = ".skill-metrics/decision-log.jsonl"

REPORT_SCHEMA_VERSION = "decision-log-report/v1"

# ── i18n ────────────────────────────────────────────────────
# Two-language string table. The CLI accepts --language en|zh|auto. New keys
# MUST be added to both languages; the resolver falls back to English if a
# translation is missing in a future language.
SUPPORTED_LANGUAGES = ("en", "zh")
DEFAULT_LANGUAGE = "en"

DIST_ICONS: dict[str, str] = {
    "decision": "🧭",
    "verifier": "✅",
    "lead":     "👥",
    "track":    "🚦",
    "risk":     "⚠️",
}

STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "title":              "Decision Log Dashboard",
        "subtitle":           "virtual-intelligent-dev-team · governance triangle in motion",
        "kpi_total_events":   "Total events",
        "kpi_total_sub":      "all-time",
        "kpi_throughput":     "Last 24 buckets",
        "kpi_throughput_sub": "hourly throughput",
        "kpi_first":          "First event",
        "kpi_first_sub":      "earliest recorded",
        "kpi_last":           "Last event",
        "kpi_last_sub":       "most recent",
        "section_dist":       "Distributions",
        "section_dist_count": "{n} cards",
        "section_trend":      "Trend",
        "section_trend_count": "hourly",
        "trend_sub":          "Throughput over the last {n} buckets",
        "trend_caption":      "Peak bucket highlighted in red. Each point = one hourly bucket.",
        "skip_link":          "Skip to main content",
        "health_healthy":     "HEALTHY",
        "health_empty":       "EMPTY",
        "card_decision":      "Decision Distribution",
        "card_verifier":      "Verifier Distribution",
        "card_lead":          "Lead Agent Distribution",
        "card_track":         "Track Distribution",
        "card_risk":          "Risk Distribution",
        "empty":              "no entries",
        "no_hourly":          "no hourly data",
        "spark_aria":         "Hourly throughput sparkline, peak {value}",
        "kpi_focus_total":    "all entries",
        "kpi_focus_recent":   "recent activity",
        "kpi_focus_history":  "historical start",
        "kpi_focus_latest":   "latest state",
        "footer":             "Generated by <code>{script}</code> · virtual-intelligent-dev-team v{version}",
        "lang_label":         "Language",
        "lang_en":            "English",
        "lang_zh":            "中文",
        "window_label":       "Time window",
        "window_7d":          "Last 7 days",
        "window_30d":         "Last 30 days",
        "window_90d":         "Last 90 days",
        "window_all":         "All time",
    },
    "zh": {
        "title":              "决策日志 Dashboard",
        "subtitle":           "virtual-intelligent-dev-team · 治理三角在运行",
        "kpi_total_events":   "总事件数",
        "kpi_total_sub":      "全部时段",
        "kpi_throughput":     "近 24 时段",
        "kpi_throughput_sub": "每小时吞吐",
        "kpi_first":          "最早事件",
        "kpi_first_sub":      "首次记录",
        "kpi_last":           "最近事件",
        "kpi_last_sub":       "最新活动",
        "section_dist":       "分布",
        "section_dist_count": "{n} 张卡片",
        "section_trend":      "趋势",
        "section_trend_count": "按小时",
        "trend_sub":          "近 {n} 个时段的吞吐",
        "trend_caption":      "峰值时段标红。每个点 = 一个小时时段。",
        "skip_link":          "跳到主内容",
        "health_healthy":     "健康",
        "health_empty":       "暂无数据",
        "card_decision":      "决策分布",
        "card_verifier":      "校验分布",
        "card_lead":          "Lead Agent 分布",
        "card_track":         "通道分布",
        "card_risk":          "风险分布",
        "empty":              "暂无数据",
        "no_hourly":          "暂无小时数据",
        "spark_aria":         "小时吞吐 sparkline，峰值 {value}",
        "kpi_focus_total":    "全部条目",
        "kpi_focus_recent":   "近期活跃",
        "kpi_focus_history":  "历史起点",
        "kpi_focus_latest":   "最新状态",
        "footer":             "由 <code>{script}</code> 生成 · virtual-intelligent-dev-team v{version}",
        "lang_label":         "语言",
        "lang_en":            "English",
        "lang_zh":            "中文",
        "window_label":       "时间窗口",
        "window_7d":          "近 7 天",
        "window_30d":         "近 30 天",
        "window_90d":         "近 90 天",
        "window_all":         "全部时间",
    },
}


def _detect_system_language() -> str:
    """Best-effort system locale detection. Falls back to English."""
    import os
    for attr in ("LC_ALL", "LANG", "LANGUAGE"):
        value = (os.environ.get(attr) or "").strip()
        if value:
            lang = value.split("_")[0].split(".")[0].lower()
            if lang in SUPPORTED_LANGUAGES:
                return lang
    try:
        loc = locale.getlocale()[0] or ""
        lang = loc.split("_")[0].lower()
        if lang in SUPPORTED_LANGUAGES:
            return lang
    except Exception:
        pass
    return DEFAULT_LANGUAGE


def resolve_language(requested: str) -> str:
    if requested == "auto":
        return _detect_system_language()
    if requested in SUPPORTED_LANGUAGES:
        return requested
    return DEFAULT_LANGUAGE


def tr(lang: str, key: str, **kwargs: Any) -> str:
    """Look up a translated string, falling back to English if a key is missing."""
    table = STRINGS.get(lang) or STRINGS[DEFAULT_LANGUAGE]
    raw = table.get(key)
    if raw is None:
        raw = STRINGS[DEFAULT_LANGUAGE].get(key, key)
    if kwargs:
        try:
            return raw.format(**kwargs)
        except (KeyError, IndexError):
            return raw
    return raw

DECISION_VALUES = (
    "route_selected",
    "delivery_accepted",
    "delivery_held",
    "release_ship",
    "release_hold",
    "fast_track_engaged",
    "fallback_engaged",
    "intent_confirmation_requested",
)
VERIFIER_VALUES = ("pass", "fail", "hold", "n_a")
RISK_VALUES = ("low", "medium", "high")
TRACK_VALUES = ("regular track", "fast track")


# ── Time window specs (id, label_key, seconds) ──────────────
# `seconds=None` means "no filtering" (all time). Used by the multi-window
# dashboard and by the --window CLI flag.
WINDOW_SPECS: tuple[tuple[str, str, int | None], ...] = (
    ("7d",  "window_7d",  7 * 86400),
    ("30d", "window_30d", 30 * 86400),
    ("90d", "window_90d", 90 * 86400),
    ("all", "window_all", None),
)
DEFAULT_WINDOW_ID = "30d"


def filter_entries_by_window(
    entries: list[dict[str, Any]],
    window_seconds: int | None,
    reference_dt: datetime | None = None,
) -> list[dict[str, Any]]:
    """Filter entries to those within the last `window_seconds` seconds.

    `reference_dt` defaults to the most recent timestamp found in the entries
    (or `now()` when no entries are timestamped). When `window_seconds` is
    `None` the input list is returned unchanged.
    """
    if window_seconds is None:
        return list(entries)
    if reference_dt is None:
        timestamps = [
            parse_iso(e["timestamp"]) for e in entries
            if isinstance(e.get("timestamp"), str)
        ]
        timestamps = [t for t in timestamps if t is not None]
        reference_dt = max(timestamps) if timestamps else datetime.now()
    cutoff = reference_dt - timedelta(seconds=window_seconds)
    kept: list[dict[str, Any]] = []
    for e in entries:
        ts = e.get("timestamp")
        if not isinstance(ts, str):
            continue
        dt = parse_iso(ts)
        if dt is None or dt < cutoff:
            continue
        kept.append(e)
    return kept


def parse_iso(value: str) -> datetime | None:
    if not isinstance(value, str) or "T" not in value:
        return None
    try:
        return datetime.fromisoformat(value)
    except Exception:
        return None


def load_entries(log_path: Path) -> tuple[list[dict[str, Any]], list[str]]:
    """Parse the log file. Returns (entries, warnings)."""
    entries: list[dict[str, Any]] = []
    warnings: list[str] = []
    if not log_path.exists():
        return entries, [f"log file not found: {log_path}"]
    try:
        with log_path.open("r", encoding="utf-8") as fh:
            for line_no, raw in enumerate(fh, start=1):
                stripped = raw.strip()
                if stripped == "":
                    continue
                try:
                    item = json.loads(stripped)
                except json.JSONDecodeError as exc:
                    warnings.append(f"line {line_no}: JSON decode error: {exc.msg}")
                    continue
                if not isinstance(item, dict):
                    warnings.append(f"line {line_no}: top-level value is not an object")
                    continue
                entries.append(item)
    except Exception as exc:
        warnings.append(f"failed to read log: {exc!r}")
        return entries, warnings
    return entries, warnings


def summarize(entries: list[dict[str, Any]]) -> dict[str, Any]:
    decisions = Counter()
    verifiers = Counter()
    leads = Counter()
    tracks = Counter()
    risks = Counter()
    hourly: dict[str, int] = {}
    first_dt: datetime | None = None
    last_dt: datetime | None = None
    skipped_dt = 0

    for entry in entries:
        decisions[entry.get("decision", "n_a")] += 1
        verifiers[entry.get("verifier", "n_a")] += 1
        leads[entry.get("lead_agent", "n_a")] += 1
        tracks[entry.get("selected_track", "n_a")] += 1
        risks[entry.get("risk_level", "n_a")] += 1

        ts = entry.get("timestamp")
        dt = parse_iso(ts) if isinstance(ts, str) else None
        if dt is None:
            skipped_dt += 1
            continue
        if first_dt is None or dt < first_dt:
            first_dt = dt
        if last_dt is None or dt > last_dt:
            last_dt = dt
        hour_key = dt.strftime("%Y-%m-%d %H:00")
        hourly[hour_key] = hourly.get(hour_key, 0) + 1

    # Keep the 24 most recent hours only.
    sorted_hours = sorted(hourly.items())[-24:]
    last_24h_throughput = sum(count for _, count in sorted_hours)

    return {
        "total_events": len(entries),
        "events_with_valid_timestamp": len(entries) - skipped_dt,
        "first_event": first_dt.isoformat(timespec="seconds") if first_dt else None,
        "last_event": last_dt.isoformat(timespec="seconds") if last_dt else None,
        "decision_distribution": dict(decisions),
        "verifier_distribution": dict(verifiers),
        "lead_distribution": dict(leads),
        "track_distribution": dict(tracks),
        "risk_distribution": dict(risks),
        "last_24h_throughput": last_24h_throughput,
        "hourly_throughput": dict(sorted_hours),
    }


# Semantic color resolver. Maps decision / verifier / risk / track values to
# CSS custom properties that the HTML template understands. Unknown keys fall
# back to a neutral info color so we never crash on new enum values.
SEMANTIC_COLORS: dict[str, dict[str, str]] = {
    "decision": {
        "route_selected": "var(--info)",
        "delivery_accepted": "var(--ok)",
        "delivery_held": "var(--warn)",
        "release_ship": "var(--ok)",
        "release_hold": "var(--err)",
        "fast_track_engaged": "var(--accent)",
        "fallback_engaged": "var(--warn)",
        "intent_confirmation_requested": "var(--muted)",
    },
    "verifier": {
        "pass": "var(--ok)",
        "fail": "var(--err)",
        "hold": "var(--warn)",
        "n_a": "var(--muted)",
    },
    "risk": {
        "low": "var(--ok)",
        "medium": "var(--warn)",
        "high": "var(--err)",
    },
    "track": {
        "regular track": "var(--info)",
        "fast track": "var(--accent)",
    },
}


def _semantic_color(category: str, key: str) -> str:
    bucket = SEMANTIC_COLORS.get(category, {})
    return bucket.get(key, "var(--info)")


def render_markdown(summary: dict[str, Any], log_path: Path, lang: str = DEFAULT_LANGUAGE) -> str:
    """Produce a Markdown summary report with semantic icons and a sparkline ASCII bar."""
    lines: list[str] = []
    lines.append(f"# 📊 {tr(lang, 'title')}")
    lines.append("")
    lines.append(f"- **Source**: `{log_path}`")
    lines.append(f"- **Generated**: {datetime.now().isoformat(timespec='seconds')}")
    lines.append(f"- **{tr(lang, 'kpi_total_events')}**: **{summary['total_events']}**")
    lines.append(
        f"- **Time range**: {summary['first_event'] or 'n/a'} → {summary['last_event'] or 'n/a'}"
    )
    lines.append(f"- **{tr(lang, 'kpi_throughput')}**: **{summary['last_24h_throughput']}**")
    lines.append("")

    def section(title: str, dist: dict[str, int], expected: tuple[str, ...] | None = None) -> None:
        lines.append(f"## {title}")
        lines.append("")
        if not dist:
            lines.append(f"> _{tr(lang, 'empty')}_")
            lines.append("")
            return
        lines.append("| Key | Count | Share | Bar |")
        lines.append("|---|---:|---:|---|")
        total = sum(dist.values()) or 1
        ordered_keys = sorted(dist.keys(), key=lambda k: (-dist[k], k))
        for key in ordered_keys:
            count = dist[key]
            share = count / total
            bar_pct = count / max(dist.values())
            bar = "▏" + "█" * int(round(bar_pct * 16)) + "▕"
            lines.append(f"| `{key}` | {count} | {share:.1%} | {bar} |")
        if expected is not None:
            for value in expected:
                if value not in dist:
                    lines.append(f"| _missing_ `{value}` | 0 | 0.0% | |")
        lines.append("")

    icon_decision = DIST_ICONS["decision"]
    icon_verifier = DIST_ICONS["verifier"]
    icon_lead     = DIST_ICONS["lead"]
    icon_track    = DIST_ICONS["track"]
    icon_risk     = DIST_ICONS["risk"]

    section(f"{icon_decision} {tr(lang, 'card_decision')}", summary["decision_distribution"], DECISION_VALUES)
    section(f"{icon_verifier} {tr(lang, 'card_verifier')}", summary["verifier_distribution"], VERIFIER_VALUES)
    section(f"{icon_lead} {tr(lang, 'card_lead')}", summary["lead_distribution"])
    section(f"{icon_track} {tr(lang, 'card_track')}", summary["track_distribution"], TRACK_VALUES)
    section(f"{icon_risk} {tr(lang, 'card_risk')}", summary["risk_distribution"], RISK_VALUES)

    lines.append(f"## ⏱ {tr(lang, 'section_trend')} ({tr(lang, 'kpi_throughput')})")
    lines.append("")
    lines.append("```")
    if summary["hourly_throughput"]:
        max_v = max(v for _, v in summary["hourly_throughput"].items()) or 1
        for hour, count in summary["hourly_throughput"].items():
            bar = "█" * int(round(count / max_v * 32))
            lines.append(f"{hour}  {count:>5}  {bar}")
    else:
        lines.append(f"  ({tr(lang, 'no_hourly')})")
    lines.append("```")
    lines.append("")
    lines.append(f"_{tr(lang, 'footer', script='inspect_decision_log.py', version='5.0.2')}_")
    lines.append("")
    return "\n".join(lines)


def render_html(
    log_path: Path,
    windows: list[tuple[str, str, dict[str, Any]]],
    lang: str = DEFAULT_LANGUAGE,
) -> str:
    """Self-contained HTML dashboard with multi-window data and bilingual switcher.

    `windows` is a list of (window_id, label_i18n_key, summary_dict) tuples.
    Each KPI / dist-card / sparkline is rendered once per window with a
    `data-window` attribute; the active window is selected by `body[data-current-window]`.
    All visible strings carry `data-i18n` attributes and a `<script id="i18n-strings">`
    blob; a small vanilla-JS block swaps them when the language radio changes.
    """
    generated = datetime.now().isoformat(timespec="seconds")
    focus_for_card = {
        "decision": "latest",
        "verifier": "latest",
        "lead":     "total",
        "track":    "history",
        "risk":     "recent",
    }

    def distribution_card_html(
        title_key: str,
        icon: str,
        dist: dict[str, int],
        category: str,
        window_id: str,
        expected: tuple[str, ...] | None = None,
    ) -> str:
        ordered_keys = sorted(dist.keys(), key=lambda k: (-dist[k], k))
        if expected:
            seen = set(ordered_keys)
            for value in expected:
                if value not in seen:
                    ordered_keys.append(value)
                    dist[value] = dist.get(value, 0)
        max_value = max(dist.values()) if dist else 1
        focus = focus_for_card[category]

        if not ordered_keys:
            body = f"<div class='empty' data-i18n='empty'>{tr(lang, 'empty')}</div>"
        else:
            rows: list[str] = []
            for key in ordered_keys:
                count = dist.get(key, 0)
                color = _semantic_color(category, key)
                pct = (count / max_value * 100) if max_value else 0
                missing = " missing" if expected and key not in dist else ""
                rows.append(
                    f"<div class='dist-row{missing}' "
                    f"data-key='{key}' "
                    f"tabindex='0' role='listitem' "
                    f"aria-label='{key}: {count}'>"
                    f"<span class='dist-key'>{key}</span>"
                    f"<span class='dist-count'>{count}</span>"
                    f"<span class='dist-bar'><span class='dist-fill' style='width:{pct:.1f}%; background:{color};'></span></span>"
                    f"</div>"
                )
            body = f"<div class='dist-body-inner' role='list'>{''.join(rows)}</div>"

        return (
            f"<section class='card dist-card' data-window='{window_id}' data-card='{category}' data-focus='{focus}' "
            f"aria-labelledby='card-title-{category}-{window_id}'>"
            f"<header class='card-head'>"
            f"<span class='card-icon' aria-hidden='true'>{icon}</span>"
            f"<h3 class='card-title' id='card-title-{category}-{window_id}' data-i18n='{title_key}'>{tr(lang, title_key)}</h3>"
            f"</header>"
            f"{body}"
            f"</section>"
        )

    def kpi_card_html(
        focus: str, kpi_class: str, label_key: str, sub_key: str,
        value_html: str, value_for_aria: str, window_id: str,
    ) -> str:
        return (
            f"<div class='kpi {kpi_class}' data-window='{window_id}' data-focus='{focus}' tabindex='0' "
            f"aria-label=\"{label_key}: {value_for_aria}\">"
            f"<div class='kpi-label' data-i18n='{label_key}'>{tr(lang, label_key)}</div>"
            f"<div class='kpi-value'>{value_html}</div>"
            f"<div class='kpi-sub' data-i18n='{sub_key}'>{tr(lang, sub_key)}</div>"
            f"</div>"
        )

    def trend_block_html(window_id: str, summary: dict[str, Any]) -> str:
        sparkline_svg = _render_sparkline(summary["hourly_throughput"], lang)
        return (
            f"<div class='trend-card-block' data-window='{window_id}'>"
            f"{sparkline_svg}"
            f"</div>"
        )

    # Build all KPI / dist / trend blocks for every window.
    kpi_html_parts: list[str] = []
    dist_html_parts: list[str] = []
    trend_html_parts: list[str] = []
    def fmt_datetime(iso_str: str | None) -> tuple[str, str]:
        """Format ISO datetime for display and aria-label.
        Returns (display_html, aria_value).
        """
        if not iso_str or iso_str == "n/a":
            return ("n/a", "n/a")
        try:
            dt = datetime.fromisoformat(iso_str)
            # Display: "06-17 18:55" (compact, no seconds)
            display = dt.strftime("%m-%d %H:%M")
            # Aria: full ISO for screen readers
            return (display, iso_str)
        except Exception:
            return (iso_str, iso_str)

    for window_id, _label_key, summary in windows:
        total = summary["total_events"]
        throughput_24h = summary["last_24h_throughput"]
        first_display, first_aria = fmt_datetime(summary["first_event"])
        last_display, last_aria = fmt_datetime(summary["last_event"])
        kpi_html_parts.extend([
            kpi_card_html("total",   "kpi-info",   "kpi_total_events", "kpi_total_sub",
                          f"{total:,}", str(total), window_id),
            kpi_card_html("recent",  "kpi-accent", "kpi_throughput",   "kpi_throughput_sub",
                          f"{throughput_24h:,}", str(throughput_24h), window_id),
            kpi_card_html("history", "kpi-ok",     "kpi_first",        "kpi_first_sub",
                          first_display, first_aria, window_id),
            kpi_card_html("latest",  "kpi-ok",     "kpi_last",         "kpi_last_sub",
                          last_display, last_aria, window_id),
        ])
        dist_html_parts.extend([
            distribution_card_html("card_decision", DIST_ICONS["decision"],
                dict(summary["decision_distribution"]), "decision", window_id, DECISION_VALUES),
            distribution_card_html("card_verifier", DIST_ICONS["verifier"],
                dict(summary["verifier_distribution"]), "verifier", window_id, VERIFIER_VALUES),
            distribution_card_html("card_lead", DIST_ICONS["lead"],
                dict(summary["lead_distribution"]), "lead", window_id),
            distribution_card_html("card_track", DIST_ICONS["track"],
                dict(summary["track_distribution"]), "track", window_id, TRACK_VALUES),
            distribution_card_html("card_risk", DIST_ICONS["risk"],
                dict(summary["risk_distribution"]), "risk", window_id, RISK_VALUES),
        ])
        trend_html_parts.append(trend_block_html(window_id, summary))

    # Switcher UIs
    lang_switcher = (
        "<div class='switcher lang-switcher' role='radiogroup' aria-label='Language'>"
        f"<input type='radio' id='lang-en' name='lang' value='en'{' checked' if lang == 'en' else ''}>"
        f"<label for='lang-en' data-i18n='lang_en'>{tr(lang, 'lang_en')}</label>"
        f"<input type='radio' id='lang-zh' name='lang' value='zh'{' checked' if lang == 'zh' else ''}>"
        f"<label for='lang-zh' data-i18n='lang_zh'>{tr(lang, 'lang_zh')}</label>"
        "</div>"
    )
    window_buttons: list[str] = []
    for window_id, label_key, _ in windows:
        checked = " checked" if window_id == DEFAULT_WINDOW_ID else ""
        window_buttons.append(
            f"<input type='radio' id='win-{window_id}' name='window' value='{window_id}'{checked}>"
            f"<label for='win-{window_id}' data-i18n='{label_key}'>{tr(lang, label_key)}</label>"
        )
    window_switcher = (
        "<div class='switcher window-switcher' role='radiogroup' aria-label='Time window'>"
        + "".join(window_buttons) +
        "</div>"
    )

    strings_json = json.dumps(STRINGS, ensure_ascii=False)
    active_window = next(
        (wid for wid, _, _ in windows if wid == DEFAULT_WINDOW_ID),
        windows[0][0] if windows else DEFAULT_WINDOW_ID,
    )
    all_summary = next((s for wid, _, s in windows if wid == "all"), None) or (windows[0][2] if windows else None)
    total_events = all_summary["total_events"] if all_summary else 0
    health_state = tr(lang, "health_healthy") if total_events > 0 else tr(lang, "health_empty")
    health_tone = "ok" if total_events > 0 else "muted"

    return f"""<!DOCTYPE html>
<html lang="{lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{tr(lang, 'title')} · virtual-intelligent-dev-team</title>
<style>
:root {{
  --fg: #0f172a;
  --fg-soft: #334155;
  --muted: #64748b;
  --muted-soft: #94a3b8;
  --bg: #f8fafc;
  --bg-elev: #f1f5f9;
  --card: #ffffff;
  --border: #e2e8f0;
  --border-soft: #f1f5f9;
  --focus-ring: #2563eb;
  --info: #3b82f6;
  --ok: #10b981;
  --warn: #f59e0b;
  --err: #ef4444;
  --accent: #8b5cf6;
  --shadow: 0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 12px rgba(15, 23, 42, 0.04);
  --shadow-hover: 0 2px 4px rgba(15, 23, 42, 0.06), 0 8px 24px rgba(15, 23, 42, 0.08);
  --radius: 12px;
  --radius-sm: 6px;
}}
* {{ box-sizing: border-box; }}
html, body {{ margin: 0; padding: 0; }}
body {{
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Inter', Roboto, "PingFang SC", "Microsoft YaHei", Helvetica, Arial, sans-serif;
  font-size: 14px;
  line-height: 1.5;
  color: var(--fg);
  background: var(--bg);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}}
.page {{ max-width: 1200px; margin: 0 auto; padding: 32px 24px 64px; }}

/* ── Skip link ────────────────────────────────────────── */
.skip-link {{
  position: absolute;
  left: -9999px;
  top: 8px;
  z-index: 100;
  padding: 8px 14px;
  background: var(--info);
  color: #fff;
  border-radius: var(--radius-sm);
  font-weight: 600;
  text-decoration: none;
  box-shadow: var(--shadow-hover);
}}
.skip-link:focus {{ left: 8px; outline: 3px solid #fff; outline-offset: 2px; }}

/* ── Universal focus ring ─────────────────────────────── */
:focus-visible {{
  outline: 3px solid var(--focus-ring);
  outline-offset: 2px;
  border-radius: var(--radius-sm);
}}

/* ── Hero ─────────────────────────────────────────────── */
.hero {{
  background: linear-gradient(135deg, #0f172a 0%, #1e293b 60%, #312e81 100%);
  color: #f8fafc;
  border-radius: var(--radius);
  padding: 32px 36px;
  margin-bottom: 32px;
  box-shadow: var(--shadow);
  position: relative;
  overflow: hidden;
}}
.hero::before {{
  content: "";
  position: absolute;
  inset: 0;
  background:
    radial-gradient(circle at 90% 10%, rgba(139, 92, 246, 0.35), transparent 45%),
    radial-gradient(circle at 10% 90%, rgba(59, 130, 246, 0.30), transparent 50%);
  pointer-events: none;
}}
.hero-inner {{ position: relative; z-index: 1; }}
.hero-title {{ font-size: clamp(22px, 3vw, 28px); font-weight: 700; margin: 0 0 8px; letter-spacing: -0.02em; }}
.hero-sub {{ color: rgba(248, 250, 252, 0.7); margin: 0 0 16px; font-size: 14px; }}
.hero-meta {{ display: flex; flex-wrap: wrap; gap: 16px 24px; font-size: 12px; color: rgba(248, 250, 252, 0.6); }}
.hero-meta code {{ color: #f8fafc; background: rgba(248, 250, 252, 0.1); padding: 2px 6px; border-radius: 4px; font-family: 'JetBrains Mono', 'SF Mono', Menlo, Consolas, monospace; }}
.hero-badge {{
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 4px 12px;
  border-radius: 999px;
  font-size: 12px;
  font-weight: 600;
  letter-spacing: 0.04em;
  background: rgba(16, 185, 129, 0.18);
  color: #6ee7b7;
  border: 1px solid rgba(16, 185, 129, 0.4);
  margin-bottom: 12px;
}}
.hero-badge.muted {{ background: rgba(100, 116, 139, 0.18); color: #cbd5e1; border-color: rgba(100, 116, 139, 0.4); }}
.hero-badge .dot {{ width: 8px; height: 8px; border-radius: 50%; background: currentColor; box-shadow: 0 0 0 3px rgba(110, 231, 183, 0.25); }}

/* ── KPI cards ────────────────────────────────────────── */
.kpi-grid {{
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 16px;
  margin-bottom: 32px;
}}
.kpi {{
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 20px 24px;
  box-shadow: var(--shadow);
  transition: box-shadow 0.2s ease, transform 0.2s ease, border-color 0.2s ease, opacity 0.2s ease;
  cursor: default;
}}
.kpi:hover {{ box-shadow: var(--shadow-hover); transform: translateY(-1px); }}
.kpi .kpi-label {{ font-size: 11px; font-weight: 600; color: var(--muted); text-transform: uppercase; letter-spacing: 0.08em; }}
.kpi .kpi-value {{ font-size: clamp(28px, 3.6vw, 36px); font-weight: 700; margin-top: 6px; font-variant-numeric: tabular-nums; letter-spacing: -0.02em; line-height: 1.1; }}
.kpi .kpi-sub {{ font-size: 12px; color: var(--muted); margin-top: 6px; }}
.kpi.kpi-info .kpi-value {{ color: var(--info); }}
.kpi.kpi-accent .kpi-value {{ color: var(--accent); }}
.kpi.kpi-ok .kpi-value {{ color: var(--ok); }}
.kpi.kpi-muted .kpi-value {{ color: var(--fg-soft); }}

/* ── Section title ────────────────────────────────────── */
.section-title {{
  font-size: 13px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: var(--muted);
  margin: 32px 0 12px;
  display: flex;
  align-items: center;
  gap: 8px;
}}
.section-title .count-pill {{
  background: var(--bg-elev);
  color: var(--fg-soft);
  padding: 2px 8px;
  border-radius: 999px;
  font-size: 11px;
  font-weight: 600;
}}

/* ── Distribution cards ───────────────────────────────── */
.dist-grid {{
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(380px, 1fr));
  gap: 16px;
  margin-bottom: 32px;
}}
.card {{
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  box-shadow: var(--shadow);
  transition: box-shadow 0.2s ease, border-color 0.2s ease, opacity 0.2s ease;
}}
.card:hover {{ box-shadow: var(--shadow-hover); }}
.card-head {{
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 16px 20px;
  border-bottom: 1px solid var(--border-soft);
}}
.card-icon {{
  width: 32px;
  height: 32px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  background: var(--bg-elev);
  border-radius: var(--radius-sm);
  font-size: 16px;
}}
.card-title {{ font-size: 14px; font-weight: 600; margin: 0; letter-spacing: -0.01em; }}
.dist-body-inner {{ padding: 8px 12px 12px; }}
.dist-row {{
  display: grid;
  grid-template-columns: minmax(0, 1fr) 56px minmax(0, 1.2fr);
  align-items: center;
  gap: 12px;
  padding: 8px 8px;
  border-radius: var(--radius-sm);
  font-variant-numeric: tabular-nums;
  transition: background 0.15s ease, font-weight 0.15s ease, opacity 0.15s ease;
  cursor: default;
}}
.dist-row:hover, .dist-row:focus-visible {{ background: var(--bg-elev); }}
.dist-row.missing .dist-key {{ color: var(--muted-soft); font-style: italic; }}
.dist-key {{ font-size: 13px; color: var(--fg-soft); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }}
.dist-count {{ text-align: right; font-weight: 600; color: var(--fg); }}
.dist-bar {{ height: 8px; background: var(--bg-elev); border-radius: 999px; overflow: hidden; }}
.dist-fill {{ display: block; height: 100%; border-radius: 999px; transition: width 0.4s ease; }}
.empty {{ color: var(--muted-soft); font-style: italic; padding: 16px; text-align: center; }}

/* ── Trend card ───────────────────────────────────────── */
.trend-card {{ padding: 20px 24px; }}
.trend-card h3 {{ margin: 0 0 4px; font-size: 14px; font-weight: 600; }}
.trend-card .trend-sub {{ font-size: 12px; color: var(--muted); margin-bottom: 16px; }}
.spark {{ width: 100%; height: 120px; display: block; }}
.spark .grid {{ stroke: var(--border); stroke-width: 1; }}
.spark .axis {{ stroke: var(--muted-soft); stroke-width: 1; stroke-dasharray: 2 4; }}
.spark .area {{ fill: url(#sparkGradient); opacity: 0.6; }}
.spark .line {{ fill: none; stroke: var(--accent); stroke-width: 2; stroke-linejoin: round; stroke-linecap: round; }}
.spark .point {{ fill: var(--accent); }}
.spark .point.peak {{ fill: var(--err); }}
.spark .label {{ font-size: 10px; fill: var(--muted); font-family: 'JetBrains Mono', 'SF Mono', Menlo, Consolas, monospace; }}

/* ── Hover linkage (CSS-only via :has()) ────────────────── */
/* When any KPI card is hovered or focused, dim siblings and highlight the
   matching dist-card by data-focus. */
.page:has(.kpi[data-focus="total"]:hover),
.page:has(.kpi[data-focus="total"]:focus-within) {{
  --hover-focus: total;
}}
.page:has(.kpi[data-focus="recent"]:hover),
.page:has(.kpi[data-focus="recent"]:focus-within) {{
  --hover-focus: recent;
}}
.page:has(.kpi[data-focus="history"]:hover),
.page:has(.kpi[data-focus="history"]:focus-within) {{
  --hover-focus: history;
}}
.page:has(.kpi[data-focus="latest"]:hover),
.page:has(.kpi[data-focus="latest"]:focus-within) {{
  --hover-focus: latest;
}}

.page:has(.kpi:hover) .kpi:not(:hover),
.page:has(.kpi:focus-within) .kpi:not(:focus-within) {{ opacity: 0.55; }}

.page:has(.kpi[data-focus="total"]:hover) .dist-card[data-focus="total"],
.page:has(.kpi[data-focus="total"]:focus-within) .dist-card[data-focus="total"],
.page:has(.kpi[data-focus="recent"]:hover) .dist-card[data-focus="recent"],
.page:has(.kpi[data-focus="recent"]:focus-within) .dist-card[data-focus="recent"],
.page:has(.kpi[data-focus="history"]:hover) .dist-card[data-focus="history"],
.page:has(.kpi[data-focus="history"]:focus-within) .dist-card[data-focus="history"],
.page:has(.kpi[data-focus="latest"]:hover) .dist-card[data-focus="latest"],
.page:has(.kpi[data-focus="latest"]:focus-within) .dist-card[data-focus="latest"] {{
  border-color: var(--info);
  box-shadow: var(--shadow-hover);
  opacity: 1;
}}

.page:has(.kpi:hover) .dist-card:not([data-focus="total"]):not([data-focus="recent"]):not([data-focus="history"]):not([data-focus="latest"]) {{ opacity: 0.55; }}

/* Specific focus highlight — keep the matching card crisp even if focus is
   ambiguous; the broad dim rule above is mostly a fallback. */
.page:has(.kpi:hover) .dist-card,
.page:has(.kpi:focus-within) .dist-card {{ opacity: 0.6; }}
.page:has(.kpi[data-focus="total"]:hover) .dist-card[data-focus="total"],
.page:has(.kpi[data-focus="recent"]:hover) .dist-card[data-focus="recent"],
.page:has(.kpi[data-focus="history"]:hover) .dist-card[data-focus="history"],
.page:has(.kpi[data-focus="latest"]:hover) .dist-card[data-focus="latest"] {{ opacity: 1; }}

/* Reverse linkage: hovering a dist-card highlights the matching KPI. */
.page:has(.dist-card[data-focus="total"]:hover) .kpi[data-focus="total"],
.page:has(.dist-card[data-focus="recent"]:hover) .kpi[data-focus="recent"],
.page:has(.dist-card[data-focus="history"]:hover) .kpi[data-focus="history"],
.page:has(.dist-card[data-focus="latest"]:hover) .kpi[data-focus="latest"] {{
  border-color: var(--accent);
  box-shadow: 0 0 0 2px rgba(139, 92, 246, 0.15), var(--shadow-hover);
  opacity: 1;
}}
.page:has(.dist-card:hover) .kpi:not([data-focus="total"]):not([data-focus="recent"]):not([data-focus="history"]):not([data-focus="latest"]),
.page:has(.dist-card:focus-within) .kpi:not(:focus-within) {{ opacity: 0.55; }}

/* Cross-card row highlight: hovering any row with a given data-key highlights
   all rows with the same key in other distribution cards. */
.page:has(.dist-row[data-key="route_selected"]:hover) .dist-row[data-key="route_selected"],
.page:has(.dist-row[data-key="route_selected"]:focus-visible) .dist-row[data-key="route_selected"],
.page:has(.dist-row[data-key="delivery_accepted"]:hover) .dist-row[data-key="delivery_accepted"],
.page:has(.dist-row[data-key="delivery_accepted"]:focus-visible) .dist-row[data-key="delivery_accepted"],
.page:has(.dist-row[data-key="delivery_held"]:hover) .dist-row[data-key="delivery_held"],
.page:has(.dist-row[data-key="delivery_held"]:focus-visible) .dist-row[data-key="delivery_held"],
.page:has(.dist-row[data-key="release_ship"]:hover) .dist-row[data-key="release_ship"],
.page:has(.dist-row[data-key="release_ship"]:focus-visible) .dist-row[data-key="release_ship"],
.page:has(.dist-row[data-key="release_hold"]:hover) .dist-row[data-key="release_hold"],
.page:has(.dist-row[data-key="release_hold"]:focus-visible) .dist-row[data-key="release_hold"],
.page:has(.dist-row[data-key="fast_track_engaged"]:hover) .dist-row[data-key="fast_track_engaged"],
.page:has(.dist-row[data-key="fast_track_engaged"]:focus-visible) .dist-row[data-key="fast_track_engaged"],
.page:has(.dist-row[data-key="fallback_engaged"]:hover) .dist-row[data-key="fallback_engaged"],
.page:has(.dist-row[data-key="fallback_engaged"]:focus-visible) .dist-row[data-key="fallback_engaged"],
.page:has(.dist-row[data-key="intent_confirmation_requested"]:hover) .dist-row[data-key="intent_confirmation_requested"],
.page:has(.dist-row[data-key="intent_confirmation_requested"]:focus-visible) .dist-row[data-key="intent_confirmation_requested"],
.page:has(.dist-row[data-key="pass"]:hover) .dist-row[data-key="pass"],
.page:has(.dist-row[data-key="pass"]:focus-visible) .dist-row[data-key="pass"],
.page:has(.dist-row[data-key="fail"]:hover) .dist-row[data-key="fail"],
.page:has(.dist-row[data-key="fail"]:focus-visible) .dist-row[data-key="fail"],
.page:has(.dist-row[data-key="hold"]:hover) .dist-row[data-key="hold"],
.page:has(.dist-row[data-key="hold"]:focus-visible) .dist-row[data-key="hold"],
.page:has(.dist-row[data-key="n_a"]:hover) .dist-row[data-key="n_a"],
.page:has(.dist-row[data-key="n_a"]:focus-visible) .dist-row[data-key="n_a"],
.page:has(.dist-row[data-key="low"]:hover) .dist-row[data-key="low"],
.page:has(.dist-row[data-key="low"]:focus-visible) .dist-row[data-key="low"],
.page:has(.dist-row[data-key="medium"]:hover) .dist-row[data-key="medium"],
.page:has(.dist-row[data-key="medium"]:focus-visible) .dist-row[data-key="medium"],
.page:has(.dist-row[data-key="high"]:hover) .dist-row[data-key="high"],
.page:has(.dist-row[data-key="high"]:focus-visible) .dist-row[data-key="high"],
.page:has(.dist-row[data-key="regular track"]:hover) .dist-row[data-key="regular track"],
.page:has(.dist-row[data-key="regular track"]:focus-visible) .dist-row[data-key="regular track"],
.page:has(.dist-row[data-key="fast track"]:hover) .dist-row[data-key="fast track"],
.page:has(.dist-row[data-key="fast track"]:focus-visible) .dist-row[data-key="fast track"] {{
  background: var(--bg-elev);
  font-weight: 600;
}}
.page:has(.dist-row:hover) .dist-row:not(:hover):not(:focus-visible) {{ opacity: 0.45; }}

/* ── Footer ───────────────────────────────────────────── */
footer {{
  margin-top: 48px;
  padding-top: 24px;
  border-top: 1px solid var(--border);
  font-size: 12px;
  color: var(--muted);
  text-align: center;
}}

/* ── Reduced motion (a11y v2) ─────────────────────────── */
@media (prefers-reduced-motion: reduce) {{
  *, *::before, *::after {{
    animation-duration: 0.01ms !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }}
}}

/* ── High contrast (a11y v2) ──────────────────────────── */
@media (prefers-contrast: more) {{
  :root {{
    --fg: #000000;
    --fg-soft: #111827;
    --muted: #1f2937;
    --border: #6b7280;
    --border-soft: #9ca3af;
    --bg-elev: #e5e7eb;
  }}
  .kpi, .card {{ border-width: 2px; }}
  :focus-visible {{ outline-width: 4px; }}
}}

@media (max-width: 640px) {{
  .page {{ padding: 16px 12px 48px; }}
  .hero {{ padding: 24px 20px; }}
  .dist-grid {{ grid-template-columns: 1fr; }}
  .kpi-grid {{ grid-template-columns: 1fr 1fr; }}
}}

/* ── Switchers (language + time window) ─────────────────── */
.hero-switchers {{
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-top: 16px;
}}
.switcher {{
  display: inline-flex;
  gap: 2px;
  background: rgba(248, 250, 252, 0.08);
  border: 1px solid rgba(248, 250, 252, 0.12);
  border-radius: 999px;
  padding: 3px;
}}
.switcher input {{ display: none; }}
.switcher label {{
  padding: 4px 12px;
  border-radius: 999px;
  font-size: 12px;
  font-weight: 500;
  cursor: pointer;
  color: rgba(248, 250, 252, 0.65);
  transition: background 0.2s, color 0.2s;
}}
.switcher input:checked + label {{
  background: rgba(248, 250, 252, 0.18);
  color: #f8fafc;
}}
.switcher label:hover {{ color: rgba(248, 250, 252, 0.9); }}

/* ── Multi-window visibility (CSS-only, no JS needed for init) ─ */
body[data-current-window="7d"] [data-window]:not([data-window="7d"]),
body[data-current-window="30d"] [data-window]:not([data-window="30d"]),
body[data-current-window="90d"] [data-window]:not([data-window="90d"]),
body[data-current-window="all"] [data-window]:not([data-window="all"]) {{
  display: none !important;
}}
</style>
</head>
<body data-current-window="{active_window}">
<a class="skip-link" href="#main" data-i18n="skip_link">{tr(lang, 'skip_link')}</a>
<main class="page" id="main" tabindex="-1">
  <header class="hero">
    <div class="hero-inner">
      <span class="hero-badge {health_tone}" aria-live="polite"><span class="dot" aria-hidden="true"></span>{health_state}</span>
      <h1 class="hero-title" data-i18n="title">{tr(lang, 'title')}</h1>
      <p class="hero-sub" data-i18n="subtitle">{tr(lang, 'subtitle')}</p>
      <div class="hero-meta">
        <span>Source: <code>{log_path}</code></span>
        <span>Generated: <code>{generated}</code></span>
      </div>
      <div class="hero-switchers">
        {lang_switcher}
        {window_switcher}
      </div>
    </div>
  </header>

  <section class="kpi-grid" aria-label="{tr(lang, 'title')} — KPIs">
    {''.join(kpi_html_parts)}
  </section>

  <h2 class="section-title">{tr(lang, 'section_dist')} <span class="count-pill">{tr(lang, 'section_dist_count', n=5)}</span></h2>
  <section class="dist-grid" aria-label="{tr(lang, 'section_dist')}">
    {''.join(dist_html_parts)}
  </section>

  <h2 class="section-title">{tr(lang, 'section_trend')} <span class="count-pill">{tr(lang, 'section_trend_count')}</span></h2>
  <section class="card trend-card" aria-labelledby="trend-title">
    <h3 id="trend-title">{tr(lang, 'trend_sub', n=24)}</h3>
    <p class="trend-sub">{tr(lang, 'trend_caption')}</p>
    {''.join(trend_html_parts)}
  </section>

  <footer>
    {tr(lang, 'footer', script='scripts/inspect_decision_log.py', version='5.0.2')}
  </footer>
</main>
<script id="i18n-strings" type="application/json">{strings_json}</script>
<script>
(function() {{
  var stringsEl = document.getElementById('i18n-strings');
  var STRINGS = stringsEl ? JSON.parse(stringsEl.textContent) : {{}};

  function applyLang(lang) {{
    var table = STRINGS[lang] || STRINGS['en'] || {{}};
    document.querySelectorAll('[data-i18n]').forEach(function(el) {{
      var key = el.getAttribute('data-i18n');
      var text = table[key] || (STRINGS['en'] && STRINGS['en'][key]) || key;
      el.textContent = text;
    }});
    document.documentElement.lang = lang;
  }}

  document.querySelectorAll('input[name="lang"]').forEach(function(radio) {{
    radio.addEventListener('change', function() {{ applyLang(this.value); }});
  }});

  document.querySelectorAll('input[name="window"]').forEach(function(radio) {{
    radio.addEventListener('change', function() {{
      document.body.setAttribute('data-current-window', this.value);
    }});
  }});
}})();
</script>
</body>
</html>
"""


def _render_sparkline(hourly: dict[str, int], lang: str = DEFAULT_LANGUAGE) -> str:
    """Render an inline SVG sparkline for the hourly throughput series.

    The SVG uses a fixed viewBox of 800x120 with linear interpolation between
    points and a gradient fill. The peak point is highlighted in red.
    """
    if not hourly:
        return f"<div class='empty'>{tr(lang, 'no_hourly')}</div>"

    items = list(hourly.items())
    width, height = 800, 120
    pad_x, pad_y = 16, 18
    inner_w = width - pad_x * 2
    inner_h = height - pad_y * 2

    max_value = max(v for _, v in items) or 1
    n = len(items)
    step_x = inner_w / max(n - 1, 1)

    points: list[tuple[float, float]] = []
    for idx, (_, value) in enumerate(items):
        x = pad_x + idx * step_x
        y = pad_y + inner_h - (value / max_value) * inner_h
        points.append((x, y))

    line_path = " ".join(
        ("M" if idx == 0 else "L") + f"{x:.1f},{y:.1f}"
        for idx, (x, y) in enumerate(points)
    )
    area_path = (
        f"M{points[0][0]:.1f},{pad_y + inner_h:.1f} "
        + " ".join(f"L{x:.1f},{y:.1f}" for x, y in points)
        + f" L{points[-1][0]:.1f},{pad_y + inner_h:.1f} Z"
    )

    peak_idx = max(range(n), key=lambda i: items[i][1])
    peak_x, peak_y = points[peak_idx]
    peak_count = items[peak_idx][1]

    # Axis baseline
    axis = (
        f'<line class="axis" x1="{pad_x}" y1="{pad_y + inner_h:.1f}" '
        f'x2="{width - pad_x}" y2="{pad_y + inner_h:.1f}"></line>'
    )

    # Min / max y-axis labels
    y_max_label = f'<text class="label" x="{pad_x}" y="{pad_y - 4}">{max_value}</text>'
    y_zero_label = f'<text class="label" x="{pad_x}" y="{pad_y + inner_h + 14}">0</text>'

    # X-axis: first, middle, last bucket label
    def x_label(idx: int) -> str:
        x, _ = points[idx]
        return f'<text class="label" x="{x:.1f}" y="{height - 2}" text-anchor="middle">{items[idx][0][-5:]}</text>'

    x_labels = ""
    if n >= 1:
        x_labels = x_label(0)
    if n >= 3:
        x_labels += x_label(n // 2)
    if n >= 2:
        x_labels += x_label(n - 1)

    dots = "".join(
        f'<circle class="point" cx="{x:.1f}" cy="{y:.1f}" r="2.5"></circle>'
        for x, y in points
    )

    aria_label = tr(lang, "spark_aria", value=peak_count)
    return (
        f'<svg class="spark" viewBox="0 0 {width} {height}" '
        f'preserveAspectRatio="none" role="img" '
        f'aria-label="{aria_label}">'
        f'<defs><linearGradient id="sparkGradient" x1="0" x2="0" y1="0" y2="1">'
        f'<stop offset="0%" stop-color="#8b5cf6" stop-opacity="0.45"/>'
        f'<stop offset="100%" stop-color="#8b5cf6" stop-opacity="0"/>'
        f'</linearGradient></defs>'
        f'<title>{aria_label}</title>'
        f'{axis}'
        f'<path class="area" d="{area_path}"></path>'
        f'<path class="line" d="{line_path}"></path>'
        f'{dots}'
        f'<circle class="point peak" cx="{peak_x:.1f}" cy="{peak_y:.1f}" r="4.5"></circle>'
        f'{y_max_label}{y_zero_label}{x_labels}'
        f'</svg>'
    )


def build_report(
    repo_path: Path,
    log_path: Path,
    markdown_output: Path | None,
    html_output: Path | None,
    lang: str = DEFAULT_LANGUAGE,
) -> dict[str, Any]:
    entries, warnings = load_entries(log_path)
    summary = summarize(entries)
    ok = True

    if markdown_output is not None:
        try:
            markdown_output.parent.mkdir(parents=True, exist_ok=True)
            markdown_output.write_text(render_markdown(summary, log_path, lang=lang), encoding="utf-8")
        except Exception as exc:
            ok = False
            warnings.append(f"failed to write markdown output: {exc!r}")

    if html_output is not None:
        try:
            html_output.parent.mkdir(parents=True, exist_ok=True)
            # Build multi-window summaries for the dashboard.
            windows: list[tuple[str, str, dict[str, Any]]] = []
            for window_id, label_key, seconds in WINDOW_SPECS:
                filtered = filter_entries_by_window(entries, seconds)
                windows.append((window_id, label_key, summarize(filtered)))
            html_output.write_text(render_html(log_path, windows, lang=lang), encoding="utf-8")
        except Exception as exc:
            ok = False
            warnings.append(f"failed to write html output: {exc!r}")

    return {
        "ok": ok,
        "schema_version": REPORT_SCHEMA_VERSION,
        "log_file": str(log_path),
        "language": lang,
        "summary": summary,
        "markdown_output": str(markdown_output) if markdown_output is not None else None,
        "html_output": str(html_output) if html_output is not None else None,
        "warnings": warnings,
    }


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo",
        default=str(SKILL_DIR),
        help="Repository root used to resolve the relative log path.",
    )
    parser.add_argument(
        "--log-file",
        default=DEFAULT_LOG_PATH,
        help="Path to the decision log (relative to --repo). Default: .skill-metrics/decision-log.jsonl",
    )
    parser.add_argument(
        "--markdown-output",
        default=None,
        help="Write a Markdown report to this path.",
    )
    parser.add_argument(
        "--html-output",
        default=None,
        help="Write a self-contained HTML dashboard to this path.",
    )
    parser.add_argument(
        "--language",
        default="auto",
        choices=("auto", "en", "zh"),
        help="Report language. 'auto' picks from system locale. Default: auto.",
    )
    parser.add_argument(
        "--pretty",
        action="store_true",
        help="Pretty-print the JSON result on stdout.",
    )
    args = parser.parse_args(argv)

    repo_path = Path(args.repo).resolve()
    log_path = repo_path / args.log_file
    markdown_path = Path(args.markdown_output).resolve() if args.markdown_output else None
    html_path = Path(args.html_output).resolve() if args.html_output else None
    lang = resolve_language(args.language)

    try:
        report = build_report(repo_path, log_path, markdown_path, html_path, lang=lang)
    except Exception as exc:
        report = {"ok": False, "error": f"unexpected inspect error: {exc!r}"}

    indent = 2 if args.pretty else None
    print(json.dumps(report, ensure_ascii=False, indent=indent))
    return 0 if report.get("ok") else 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))